# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_messagelog_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delay_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
